language: cpp
compiler:
- g++

before_install:
- sudo apt-get update
- sudo apt-get install valgrind
- sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
- sudo apt-get update -qq
- sudo apt-get install -qq g++-4.8
- export CXX="g++-4.8"

script: mkdir build && cd build && cmake ../ && make test
